/**Get AVAILABILITY_SCHEDULE */
export const GET_AVAILABILITY_SCHEDULE_GLOBAL = 'GET_AVAILABILITY_SCHEDULE_GLOBAL';
export const GET_AVAILABILITY_SCHEDULE_GLOBAL_SUCCESS = 'GET_AVAILABILITY_SCHEDULE_GLOBAL_SUCCESS';

/**create AVAILABILITY_SCHEDULE */
export const CREATE_AVAILABILITY_SCHEDULE_GLOBAL = 'CREATE_AVAILABILITY_SCHEDULE_GLOBAL';
export const CREATE_AVAILABILITY_SCHEDULE_GLOBAL_SUCCESS = 'CREATE_AVAILABILITY_SCHEDULE_GLOBAL_SUCCESS';