export const BASE_URL = 'http://localhost:8200/api/';
export const data = {
  funding: [
    {
      name: 's',
      type: 's',
      contact: 's',
      email: 'abhsashCdddDFG@gmail.com',
      website: 'd',
      phoneNumber: '+37477379237',
      address: {
        lat: 0,
        lng: 0,
        street: 'string',
        city: 'string',
        state: 'string',
        zip: 'string',
        country: 'string',
        formattedAddress: 'string',
      },
      status: 0,
    },
    {
      id: null,
      name: 'aaaaaaaaaaassssssssssssddddddddddddffffffffffffff',
      type: 's',
      contact: 's',
      email: 'abhhsdsacdsxCdddDFG@gmail.com',
      website: 'd',
      phoneNumber: '+37477379237',
      address: {
        lat: 0,
        lng: 0,
        street: 'string',
        city: 'string',
        state: 'string',
        zip: 'string',
        country: 'string',
        formattedAddress: 'string',
      },
      status: 0,
    },
  ],
  fundingService: [
    {
      funderId: null,
      id: '612e2b4543fc954ad068f356',
      name: 'string',
      globServiceId: null,
      rate: 0,
      cptCode: 0,
      size: 0,
      min: 0,
      max: 0,
    },
    {
      name: 'string',
      globServiceId: null,
      rate: 0,
      cptCode: 0,
      size: 0,
      min: 0,
      max: 0,
    },
  ],
  globalService: [
    {
      name: 'ok',
      displayCode: 'chokay',
      category: 'ha lav okay',
    },
    {
      name: null,
      displayCode: null,
      category: null,
    },
  ],
  modifier: [
    {
      modifiers: [
        {
          credentialId: null,
          chargeRate: 0,
          name: 'string',
          type: 0,
        },
        {
          credentialId: null,
          chargeRate: 10,
          name: 'eeeh',
          type: 0,
        },
      ],
      serviceId: null,
    },
  ],
  credential: [
    {
      name: 'a',
      type: 2,
    },
    {
      name: null,
      type: null,
    },
  ],
  department: [
    {
      name: 'department',
    },
    {
      name: null,
    },
  ],
  staff: [
    {
      password: 'dabndiwnudnaowind',
      firstName: 'A',
      middleName: 'A',
      lastName: 'A',
      email: 'A@gmail.com',
      secondaryEmail: 'B@gmail.com',
      phone: '+14845219791',
      secondaryPhone: '+14845219791',
      state: 'string',
      gender: 'string',
      birthday: '2021-09-12T08:05:11.088Z',
      residency: 'string',
      ssn: 0,
      address: {
        lat: 0,
        lng: 0,
        street: 'string',
        city: 'string',
        state: 'string',
        zip: 'string',
        country: 'string',
        formattedAddress: 'string',
      },
    },
    {
      password: 'dabndiwnudnaowind',
      firstName: 'B',
      middleName: 'B',
      lastName: 'B',
      email: 'B@gmail.com',
      secondaryEmail: 'B@gmail.com',
      phone: '+14845219791',
      secondaryPhone: '+14845219791',
      state: 'string',
      gender: 'string',
      birthday: '2021-09-12T08:05:11.088Z',
      residency: 'string',
      ssn: 0,
      address: {
        lat: 0,
        lng: 0,
        street: 'string',
        city: 'string',
        state: 'string',
        zip: 'string',
        country: 'string',
        formattedAddress: 'string',
      },
    },
  ],
  comment: [
    {
      text: 'Comment Create',
      subject: 'Comment SUbject',
      resource: null,
      onModel: 'Staff',
    },
    {
      text: 'Comment Create 1',
      subject: 'Comment SUbject',
      resource: null,
      onModel: null,
    },
  ],
  permissions: [
    {
      title: 'ALL_ACCESS',
      description: 'Used for super admin',
      code: 0,
    },
    {
      title: 'MANAGE_ROLES',
      description: 'Used for users to manage role system',
      code: 1,
    },
    {
      title: 'MANAGE_ADMINS',
      description: 'Used for users to manage admins',
      code: 2,
    },
    {
      title: 'MANAGE_FUNDERS',
      description: 'Can create, delete and update funding sources related information',
      code: 3,
    },
    {
      title: 'MANAGE_CLIENTS',
      description: 'Can create, delete and update clients related information',
      code: 4,
    },
  ],
  roles: {
    SUPER_ADMIN: {
      title: 'SUPER_ADMIN',
      description: 'manage all endpoints',
      permissions: [],
    },
    MANAGE_AGENTS: {
      title: 'MANAGE_AGENTS',
      description: 'aaa',
      permissions: [],
    },
    MANAGE_OFFICE: {
      title: 'MANAGE_OFFICE',
      description: '000',
      permissions: [],
    },
  },
};
