export const dummyData = {
   CLAIMS: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(() => ({
      _id: Math.random().toString(),
      dateRange: { early: "10/21/2021", latest: "03/28/2022" },
      staff: { _id: Math.random().toString(), middleName: "Alice Johansson" },
      funder: { _id: Math.random().toString(), middleName: "Blue Cross" },
      client: { _id: Math.random().toString(), middleName: "Daniel Clark" },
      totalCharge: 300,
      ammountPaid: 100,
      remaining: 300,
      status: "Submitted",
      paymentRef: "www.testlink.com",
      receivables: [1, 2, 3].map(() => ({
         _id: Math.random().toString(),
         dateOfService: { start: "10/21/2021", end: "03/28/2022" },
         placeService: "In Home (02)",
         cptCode: "H2001",
         modifier: "HM",
         totalUnits: 8,
         totalBill: 1000,
         renderingProvider: "12312312",
         bills: [1, 2, 3].map(() => ({
            _id: Math.random().toString(),
            dateOfService: "10/21/2022",
            timeOfService: "09:00 AM - 10:00 AM",
            units: 4,
            signature: "file_pdf.pdf",
         })),
      })),
   })),
};
