export const dummyBillTransactions = [
   {
      _id: "12",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: false,
   },
   {
      _id: "23",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: true,
   },
   {
      _id: "34",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: false,
   },
   {
      _id: "45",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: false,
   },
   {
      _id: "56",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
      isVoided: true,
   },
   {
      _id: "67",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
      isVoided: false,
   },
   {
      _id: "78",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: false,
   },
   {
      _id: "89",
      date: "10/21/2021",
      creator: "Alice Johansson",
      type: "Client Responsibility",
      amount: 200,
      paymentRefNumber: "123123431",
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
      isVoided: true,
   },
];
