export const dummyBills = [
   {
      _id: "1",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      _id: "2",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      _id: "3",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      _id: "4",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      _id: "5",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      _id: "6",
      dateOfService: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      authService: "H2212 (HM)",
      totalHours: "3.5",
      totalUnits: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payerTotal: "$ 200.00",
      clientResp: "$ 50.00",
      billedAmount: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
];
