export const DUMMY_BILLS = [
   {
      id: 1,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      id: 2,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      id: 3,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      id: 4,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      id: 5,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
   {
      id: 6,
      date: "10/21/2021",
      payor: "Blue Shield",
      client: "D. Clark",
      service: "H2212 (HM)",
      hours: "3.5",
      units: "6",
      billedRate: "$ 50.00",
      totalAmount: "$ 300.00",
      payorBalance: "$ 200.00",
      clientBalance: "$ 50.00",
      totalBalance: "$ 50.00",
      claimStatus: "Complete",
      invoiceStatus: "Not Invoiced",
      status: "Open",
   },
];
