/**Get clients */
export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';

/**Create clients */
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';

/**Delete clients */
export const DELETE_CLIENT = 'DELETE_CLIENT';

/**Edit clients */
export const EDIT_CLIENT = 'EDIT_CLIENT';

/**get client by id */
export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID';
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS';

/**get client contacts */
export const GET_CLIENT_CONTACTS = 'GET_CLIENT_CONTACTS';
export const GET_CLIENT_CONTACTS_SUCCESS = 'GET_CLIENT_CONTACTS_SUCCESS';

/** Create client contact **/
export const CREATE_CLIENT_CONTACT = 'CREATE_CLIENT_CONTACT'
export const CREATE_CLIENT_CONTACT_SUCCESS = 'CREATE_CLIENT_CONTACT_SUCCESS'

/** Edit client contact **/
export const EDIT_CLIENT_CONTACT = 'EDIT_CLIENT_CONTACT'

/** Delete client contact **/
export const DELETE_CLIENT_CONTACT = 'DELETE_CLIENT_CONTACT'

/**get client enrollment */
export const GET_CLIENT_ENROLLMENT = 'GET_CLIENT_ENROLLMENT';
export const GET_CLIENT_ENROLLMENT_SUCCESS = 'GET_CLIENT_ENROLLMENT_SUCCESS';

/** Create client enrollment **/
export const CREATE_CLIENT_ENROLLMENT = 'CREATE_CLIENT_ENROLLMENT'

/** Edit client enrollment **/
export const EDIT_CLIENT_ENROLLMENT = 'EDIT_CLIENT_ENROLLMENT'

/** Delete client enrollment **/
export const DELETE_CLIENT_ENROLLMENT = 'DELETE_CLIENT_ENROLLMENT'

/**get client Authorizations */
export const GET_CLIENT_AUTHORIZATION = 'GET_CLIENT_AUTHORIZATION';
export const GET_CLIENT_AUTHORIZATION_SUCCESS = 'GET_CLIENT_AUTHORIZATION_SUCCESS';
export const GET_CLIENT_AUTHORIZATION_ERROR = 'GET_CLIENT_AUTHORIZATION_ERROR';

/**create client Authorizations */
export const CREATE_CLIENT_AUTHORIZATION = 'CREATE_CLIENT_AUTHORIZATION';

/**edit client Authorizations */
export const EDIT_CLIENT_AUTHORIZATION = 'EDIT_CLIENT_AUTHORIZATION';

/**delete client Authorizations */
export const DELETE_CLIENT_AUTHORIZATION = 'DELETE_CLIENT_AUTHORIZATION';

/**get client Authorizations Service */
export const GET_CLIENT_AUTHORIZATION_SERV = 'GET_CLIENT_AUTHORIZATION_SERV';
export const GET_CLIENT_AUTHORIZATION_SERV_SUCCESS = 'GET_CLIENT_AUTHORIZATION_SERV_SUCCESS';
export const GET_CLIENT_AUTHORIZATION_SERV_ERROR = 'GET_CLIENT_AUTHORIZATION_SERV_ERROR';

/**create client Authorizations Service */
export const CREATE_CLIENT_AUTHORIZATION_SERV = 'CREATE_CLIENT_AUTHORIZATION_SERV';

/**edit client Authorizations service */
export const EDIT_CLIENT_AUTHORIZATION_SERV = 'EDIT_CLIENT_AUTHORIZATION_SERV';

/**delete client Authorizations service */
export const DELETE_CLIENT_AUTHORIZATION_SERV = 'DELETE_CLIENT_AUTHORIZATION_SERV';

/**create client Authorization File */
export const CREATE_CLIENT_AUTHORIZATION_FILE = 'CREATE_CLIENT_AUTHORIZATION_FILE';
export const CREATE_CLIENT_AUTHORIZATION_FILE_SUCCESS = 'CREATE_CLIENT_AUTHORIZATION_FILE_SUCCESS';

/**get client Authorization File */
export const GET_CLIENT_AUTHORIZATION_FILE = 'GET_CLIENT_AUTHORIZATION_FILE';
export const GET_CLIENT_AUTHORIZATION_FILE_SUCCESS = 'GET_CLIENT_AUTHORIZATION_FILE_SUCCESS';

/**edit client Authorization File */
export const EDIT_CLIENT_AUTHORIZATION_FILE = 'EDIT_CLIENT_AUTHORIZATION_FILE';
export const EDIT_CLIENT_AUTHORIZATION_FILE_SUCCESS = 'EDIT_CLIENT_AUTHORIZATION_FILE_SUCCESS';

/**delete client Authorization File */
export const DELETE_CLIENT_AUTHORIZATION_FILE = 'DELETE_CLIENT_AUTHORIZATION_FILE';
export const DELETE_CLIENT_AUTHORIZATION_FILE_SUCCESS = 'DELETE_CLIENT_AUTHORIZATION_FILE_SUCCESS';

/**get client histories */
export const GET_CLIENT_HISTORIES = 'GET_CLIENT_HISTORIES';
export const GET_CLIENT_HISTORIES_SUCCESS = 'GET_CLIENT_HISTORIES_SUCCESS';


/**get  Auth Service Mo Check */
export const GET_CLIENT_AUTHORIZATION_MOD_CHECK = 'GET_CLIENT_AUTHORIZATION_MOD_CHECK';