/**Create fundingService */
export const CREATE_FUNDING_SERVICE = "CREATE_FUNDING_SERVICE";

/**Edit fundingService */
export const EDIT_FUNDING_SERVICE = "EDIT_FUNDING_SERVICE";

/**Get fundingService */
export const GET_FUNDING_SERVICES = "GET_FUNDING_SERVICES";
export const GET_FUNDING_SERVICES_SUCCESS = "GET_FUNDING_SERVICES_SUCCESS";

/**Get fundingServiceById */
export const GET_FUNDING_SERVICE_BY_ID = "GET_FUNDING_SERVICE_BY_ID";
export const GET_FUNDING_SERVICE_BY_ID_SUCCESS = "GET_FUNDING_SERVICE_BY_ID_SUCCESS";
