/**Create Global Credential */
export const CREATE_CREDENTIAL_GLOBAL = 'CREATE_CREDENTIAL_GLOBAL'
export const CREATE_CREDENTIAL_GLOBAL_SUCCESS = 'CREATE_CREDENTIAL_GLOBAL_SUCCESS'

/**Get Global Credential */
export const GET_CREDENTIAL = 'GET_CREDENTIAL'
export const GET_CREDENTIAL_SUCCESS = 'GET_CREDENTIAL_SUCCESS'

/**Edit Global Credential by id */
export const EDIT_CREDENTIAL_BY_ID_GLOBAL = 'EDIT_CREDENTIAL_BY_ID_GLOBAL'
export const EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS = 'EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS'
