// CREDENTIALS

/**Create Global Credential */
export const CREATE_CREDENTIAL_GLOBAL = 'CREATE_CREDENTIAL_GLOBAL'
export const CREATE_CREDENTIAL_GLOBAL_SUCCESS = 'CREATE_CREDENTIAL_GLOBAL_SUCCESS'

/**Get Global Credential */
export const GET_CREDENTIAL_GLOBAL = 'GET_CREDENTIAL_GLOBAL'
export const GET_CREDENTIAL_GLOBAL_SUCCESS = 'GET_CREDENTIAL_GLOBAL_SUCCESS'

/**Edit Global Credential by id */
export const EDIT_CREDENTIAL_BY_ID_GLOBAL = 'EDIT_CREDENTIAL_BY_ID_GLOBAL'
export const EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS = 'EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Credential by id */
export const DELETE_CREDENTIAL_BY_ID_GLOBAL = 'DELETE_CREDENTIAL_BY_ID_GLOBAL'
export const DELETE_CREDENTIAL_BY_ID_GLOBAL_SUCCESS = 'DELETE_CREDENTIAL_BY_ID_GLOBAL_SUCCESS'

// SERVICES

/**Create Global Service */
export const CREATE_SERVICE_GLOBAL = 'CREATE_SERVICE_GLOBAL'
export const CREATE_SERVICE_GLOBAL_SUCCESS = 'CREATE_SERVICE_GLOBAL_SUCCESS'

/**Get Global Services */
export const GET_SERVICES = 'GET_SERVICES'
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS'

/**Edit Global Services by id */
export const EDIT_SERVICE_BY_ID_GLOBAL = 'EDIT_SERVICE_BY_ID_GLOBAL'
export const EDIT_SERVICE_BY_ID_GLOBAL_SUCCESS = 'EDIT_SERVICE_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Service by id */
export const DELETE_SERVICE_BY_ID_GLOBAL = 'DELETE_SERVICE_BY_ID_GLOBAL'
export const DELETE_SERVICE_BY_ID_GLOBAL_SUCCESS = 'DELETE_SERVICE_BY_ID_GLOBAL_SUCCESS'

// DEPARTMENTS

/**Create Global Services */
export const CREATE_DEPARTMENT_GLOBAL = 'CREATE_DEPARTMENT_GLOBAL'
export const CREATE_DEPARTMENT_GLOBAL_SUCCESS = 'CREATE_DEPARTMENT_GLOBAL_SUCCESS'

/**Get Global Services */
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENTS_SUCCESS = 'GET_DEPARTMENTS_SUCCESS'

/**Edit Global Services by id */
export const EDIT_DEPARTMENT_BY_ID_GLOBAL = 'EDIT_DEPARTMENT_BY_ID_GLOBAL'
export const EDIT_DEPARTMENT_BY_ID_GLOBAL_SUCCESS = 'EDIT_DEPARTMENT_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Service by id */
export const DELETE_DEPARTMENT_BY_ID_GLOBAL = 'DELETE_DEPARTMENT_BY_ID_GLOBAL'
export const DELETE_DEPARTMENT_BY_ID_GLOBAL_SUCCESS = 'DELETE_DEPARTMENT_BY_ID_GLOBAL_SUCCESS'

// JOB

/**Create Global Job */
export const CREATE_JOB_GLOBAL = 'CREATE_JOB_GLOBAL'
export const CREATE_JOB_GLOBAL_SUCCESS = 'CREATE_JOB_GLOBAL_SUCCESS'

/**Get Global Jobs */
export const GET_JOBS = 'GET_JOBS'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

/**Edit Global Job by id */
export const EDIT_JOB_BY_ID_GLOBAL = 'EDIT_JOB_BY_ID_GLOBAL'
export const EDIT_JOB_BY_ID_GLOBAL_SUCCESS = 'EDIT_JOB_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Job by id */
export const DELETE_JOB_BY_ID_GLOBAL = 'DELETE_JOB_BY_ID_GLOBAL'
export const DELETE_JOB_BY_ID_GLOBAL_SUCCESS = 'DELETE_JOB_BY_ID_GLOBAL_SUCCESS'

// PLACE

/**Create Global Job */
export const CREATE_PLACE_GLOBAL = 'CREATE_PLACE_GLOBAL'

/**Get Global Jobs */
export const GET_PLACES = 'GET_PLACES'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'

/**Edit Global Job by id */
export const EDIT_PLACE_BY_ID_GLOBAL = 'EDIT_PLACE_BY_ID_GLOBAL'

/**Delete Global Job by id */
export const DELETE_PLACE_BY_ID_GLOBAL = 'DELETE_PLACE_BY_ID_GLOBAL'

