/**Create Global Credential */
export const CREATE_CREDENTIAL_GLOBAL = 'CREATE_CREDENTIAL_GLOBAL'
export const CREATE_CREDENTIAL_GLOBAL_SUCCESS = 'CREATE_CREDENTIAL_GLOBAL_SUCCESS'

/**Get Global Credential */
export const GET_CREDENTIAL = 'GET_CREDENTIAL'
export const GET_CREDENTIAL_SUCCESS = 'GET_CREDENTIAL_SUCCESS'

/**Edit Global Credential by id */
export const EDIT_CREDENTIAL_BY_ID_GLOBAL = 'EDIT_CREDENTIAL_BY_ID_GLOBAL'
export const EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS = 'EDIT_CREDENTIAL_BY_ID_GLOBAL_SUCCESS'

/**Create Global Service */
export const CREATE_SERVICE_GLOBAL = 'CREATE_SERVICE_GLOBAL'
export const CREATE_SERVICE_GLOBAL_SUCCESS = 'CREATE_SERVICE_GLOBAL_SUCCESS'

/**Get Global Services */
export const GET_SERVICES = 'GET_SERVICES'
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS'

/**Edit Global Services by id */
export const EDIT_SERVICE_BY_ID_GLOBAL = 'EDIT_SERVICE_BY_ID_GLOBAL'
export const EDIT_SERVICE_BY_ID_GLOBAL_SUCCESS = 'EDIT_SERVICE_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Credential by id */
export const DELETE_SERVICE_BY_ID_GLOBAL = 'DELETE_SERVICE_BY_ID_GLOBAL'
export const DELETE_SERVICE_BY_ID_GLOBAL_SUCCESS = 'DELETE_SERVICE_BY_ID_GLOBAL_SUCCESS'
