
/**Create fundingSource */
export const CREATE_FUNDING_SOURCE = 'CREATE_FUNDING_SOURCE';
export const CREATE_FUNDING_SOURCE_SUCCESS = 'CREATE_FUNDING_SOURCE_SUCCESS';

/**Edit fundingSource */
export const EDIT_FUNDING_SOURCE = 'EDIT_FUNDING_SOURCE';



/**Get fundingSource */
export const GET_FUNDING_SOURCE = 'GET_FUNDING_SOURCE';
export const GET_FUNDING_SOURCE_SUCCESS = 'GET_FUNDING_SOURCE_SUCCESS';


/**Get fundingSourceById */
export const GET_FUNDING_SOURCE_BY_ID = 'GET_FUNDING_SOURCE_BY_ID';
export const GET_FUNDING_SOURCE_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_BY_ID_SUCCESS';


/**Get funding SourceServices By Id */
export const GET_FUNDING_SOURCE_SERVICE_BY_ID = 'GET_FUNDING_SOURCE_SERVICE_BY_ID';
export const GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS';

/**Create fundingSourceServices By Id */
export const CREATE_FUNDING_SOURCE_SERVICE_BY_ID = 'CREATE_FUNDING_SOURCE_SERVICE_BY_ID';

/**Edit funding Source Services By Id */
export const EDIT_FUNDING_SOURCE_SERVICE = 'EDIT_FUNDING_SOURCE_SERVICE';

/**delete funding Source ServicesById */
export const DELETE_FUNDING_SOURCE_SERVICE = 'DELETE_FUNDING_SOURCE_SERVICE';

/**Create funding SourceServices Modifier */
export const CREATE_FUNDING_SOURCE_SERVICE_MODIFIER = 'CREATE_FUNDING_SOURCE_SERVICE_BY_ID';


/**Get funding Source Histories By Id */
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID = 'GET_FUNDING_SOURCE_HISTORIES_BY_ID';
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS';


/**Get funding SourceServ */
export const GET_FUNDING_SOURCE_SERV = 'GET_FUNDING_SOURCE_SERV';
export const GET_FUNDING_SOURCE_SERV_SUCCESS = 'GET_FUNDING_SOURCE_SERV_SUCCESS';


/**Get funding SourceServById */
export const GET_FUNDING_SOURCE_SERV_BY_ID = 'GET_FUNDING_SOURCE_SERV_BY_ID';
export const GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS';


/**Create funding SourceServ */
export const CREATE_FUNDING_SOURCE_SERV = 'CREATE_FUNDING_SOURCE_SERV';


export const GET_ACTIVE_OR_INACTIVE = 'GET_ACTIVE_OR_INACTIVE'

/**Get funding Source Notes */
export const GET_FUNDING_SOURCE_NOTES = 'GET_FUNDING_SOURCE_NOTES';
export const GET_FUNDING_SOURCE_NOTES_SUCCESS = 'GET_FUNDING_SOURCE_NOTES_SUCCESS';

/**create funding Source Notes */
export const CREATE_FUNDING_SOURCE_NOTE = 'CREATE_FUNDING_SOURCE_NOTE';
export const CREATE_FUNDING_SOURCE_NOTES_SUCCESS = 'CREATE_FUNDING_SOURCE_NOTES_SUCCESS';

/**edit funding Source Notes */
export const EDIT_FUNDING_SOURCE_NOTE = 'EDIT_FUNDING_SOURCE_NOTE';

/**delete funding Source Notes */
export const DELETE_FUNDING_SOURCE_NOTE = 'DELETE_FUNDING_SOURCE_NOTE';

