/**Create fundingSource */
export const CREATE_FUNDING_SOURCE = "CREATE_FUNDING_SOURCE";

/**Edit fundingSource */
export const EDIT_FUNDING_SOURCE = "EDIT_FUNDING_SOURCE";

/**Get fundingSource */
export const GET_FUNDING_SOURCE = "GET_FUNDING_SOURCE";
export const GET_FUNDING_SOURCE_SUCCESS = "GET_FUNDING_SOURCE_SUCCESS";

/**Get fundingSourceById */
export const GET_FUNDING_SOURCE_BY_ID = "GET_FUNDING_SOURCE_BY_ID";
export const GET_FUNDING_SOURCE_BY_ID_SUCCESS = "GET_FUNDING_SOURCE_BY_ID_SUCCESS";

/**Get funding SourceServices By Id */
export const GET_FUNDING_SOURCE_SERVICE_BY_ID_NO_LOAD =
   "GET_FUNDING_SOURCE_SERVICE_BY_ID_NO_LOAD";
export const GET_FUNDING_SOURCE_SERVICE_BY_ID = "GET_FUNDING_SOURCE_SERVICE_BY_ID";
export const GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS =
   "GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS";

/**Create fundingSourceServices By Id */
export const CREATE_FUNDING_SOURCE_SERVICE_BY_ID = "CREATE_FUNDING_SOURCE_SERVICE_BY_ID";
export const CREATE_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS =
   "CREATE_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS";

/**Edit funding Source Services By Id */
export const EDIT_FUNDING_SOURCE_SERVICE = "EDIT_FUNDING_SOURCE_SERVICE";

/**delete funding Source ServicesById */
export const DELETE_FUNDING_SOURCE_SERVICE = "DELETE_FUNDING_SOURCE_SERVICE";

/**Create funding SourceServices Modifier */
export const CREATE_FUNDING_SOURCE_SERVICE_MODIFIER =
   "CREATE_FUNDING_SOURCE_SERVICE_MODIFIER";

/**edit funding SourceServices Modifier */
export const EDIT_FUNDING_SOURCE_SERVICE_MODIFIER =
   "EDIT_FUNDING_SOURCE_SERVICE_MODIFIER";

/**get funding Source Services Modifier */
export const GET_FUNDING_SOURCE_SERVICE_MODIFIERS =
   "GET_FUNDING_SOURCE_SERVICE_MODIFIERS";
export const GET_FUNDING_SOURCE_SERVICE_MODIFIERS_SUCCESS =
   "GET_FUNDING_SOURCE_SERVICE_MODIFIERS_SUCCESS";
export const GET_FUNDING_SOURCE_SERVICE_MODIFIERS_ERR =
   "GET_FUNDING_SOURCE_SERVICE_MODIFIERS_ERR";
export const GET_FUNDING_SOURCE_SERVICE_MODIFIERS_CLIENT =
   "GET_FUNDING_SOURCE_SERVICE_MODIFIERS_CLIENT";

/**Get funding Source Histories By Id */
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID = "GET_FUNDING_SOURCE_HISTORIES_BY_ID";
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS =
   "GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS";

/**Get funding SourceServ */
export const GET_FUNDING_SOURCE_SERV = "GET_FUNDING_SOURCE_SERV";
export const GET_FUNDING_SOURCE_SERV_SUCCESS = "GET_FUNDING_SOURCE_SERV_SUCCESS";

/**Get funding SourceServById */
export const GET_FUNDING_SOURCE_SERV_BY_ID = "GET_FUNDING_SOURCE_SERV_BY_ID";
export const GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS =
   "GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS";

/**Create funding SourceServ */
export const CREATE_FUNDING_SOURCE_SERV = "CREATE_FUNDING_SOURCE_SERV";

/** GET ACTIVE OR INACTIVE */
export const GET_ACTIVE_OR_INACTIVE = "GET_ACTIVE_OR_INACTIVE";

/** Edit ACTIVE OR INACTIVE */
export const EDIT_ACTIVE_OR_INACTIVE = "EDIT_ACTIVE_OR_INACTIVE";

/** Edit State */
export const SET_STATUS = "SET_STATUS";

/**Create fundingModifier */
export const CREATE_FUNDING_MODIFIER = "CREATE_FUNDING_MODIFIER";

/**Edit fundingModifier */
export const EDIT_FUNDING_MODIFIER = "EDIT_FUNDING_MODIFIER";

/**Delete fundingModifier */
export const DELETE_FUNDING_MODIFIER = "DELETE_FUNDING_MODIFIER";
