
/**Create fundingSource */
export const CREATE_FUNDING_SOURCE = 'CREATE_FUNDING_SOURCE';
export const CREATE_FUNDING_SOURCE_SUCCESS = 'CREATE_FUNDING_SOURCE_SUCCESS';

/**Edit fundingSource */
export const EDIT_FUNDING_SOURCE = 'EDIT_FUNDING_SOURCE';



/**Get fundingSource */
export const GET_FUNDING_SOURCE = 'GET_FUNDING_SOURCE';
export const GET_FUNDING_SOURCE_SUCCESS = 'GET_FUNDING_SOURCE_SUCCESS';


/**Get fundingSourceById */
export const GET_FUNDING_SOURCE_BY_ID = 'GET_FUNDING_SOURCE_BY_ID';
export const GET_FUNDING_SOURCE_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_BY_ID_SUCCESS';


/**Get fundingSourceServicesById */
export const GET_FUNDING_SOURCE_SERVICE_BY_ID = 'GET_FUNDING_SOURCE_SERVICE_BY_ID';
export const GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_SERVICE_BY_ID_SUCCESS';

/**Create fundingSourceServicesById */
export const CREATE_FUNDING_SOURCE_SERVICE_BY_ID = 'CREATE_FUNDING_SOURCE_SERVICE_BY_ID';

/**Edit fundingSourceServicesById */
export const EDIT_FUNDING_SOURCE_SERVICE = 'EDIT_FUNDING_SOURCE_SERVICE';

/**Create fundingSourceServicesModifier */
export const CREATE_FUNDING_SOURCE_SERVICE_MODIFIER = 'CREATE_FUNDING_SOURCE_SERVICE_BY_ID';


/**Get fundingSourceHistoriesById */
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID = 'GET_FUNDING_SOURCE_HISTORIES_BY_ID';
export const GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_HISTORIES_BY_ID_SUCCESS';


/**Get fundingSourceServ */
export const GET_FUNDING_SOURCE_SERV = 'GET_FUNDING_SOURCE_SERV';
export const GET_FUNDING_SOURCE_SERV_SUCCESS = 'GET_FUNDING_SOURCE_SERV_SUCCESS';


/**Get fundingSourceServById */
export const GET_FUNDING_SOURCE_SERV_BY_ID = 'GET_FUNDING_SOURCE_SERV_BY_ID';
export const GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS = 'GET_FUNDING_SOURCE_SERV_BY_ID_SUCCESS';


/**Create fundingSourceServ */
export const CREATE_FUNDING_SOURCE_SERV = 'CREATE_FUNDING_SOURCE_SERV';


export const GET_ACTIVE_OR_INACTIVE = 'GET_ACTIVE_OR_INACTIVE'
