export const data = {
    funding: [
        {
            name: "s",
            type: "s",
            contact: "s",
            email: "abhsashCdddDFG@gmail.com",
            website: "d",
            phoneNumber: "+37477379237",
            address: {
                lat: 0,
                lng: 0,
                street: "string",
                city: "string",
                state: "string",
                zip: "string",
                country: "string",
                formattedAddress: "string"
            },
            status: 0
        },
        {
            id: "6116a626aee275155032b87c",
            name: "ok",
            type: "s",
            contact: "s",
            email: "abhhsdsacdsxCdddDFG@gmail.com",
            website: "d",
            phoneNumber: "+37477379237",
            address: {
                lat: 0,
                lng: 0,
                street: "string",
                city: "string",
                state: "string",
                zip: "string",
                country: "string",
                formattedAddress: "string"
            },
            status: 0
        },
        {
            firstName: 'Admin',
            lastName: 'Two',
            username: 'Admin 2',
            email: 'admin2@test.com',
            phoneNumber: '8183421231',
            ssn: 212312323,
            dl: '2342342',
            address: '1057 western ave glendale',
            password: 'test_password1',
        },
        {
            firstName: 'Admin',
            lastName: 'Three',
            username: 'Admin 3',
            email: 'admin3@test.com',
            phoneNumber: '8183421231',
            ssn: 212312323,
            dl: '2342342',
            address: '1057 western ave glendale',
            password: 'test_password1',
        },
    ],
    offices: [
        {
            name: 'First Office',
            email: 'office1@test.com',
            phoneNumber: '8184417656',
            establishedDate: 0,
            address: '1000 los angeles',
        },
        {
            name: 'Second Office',
            email: 'office1@test.com',
            phoneNumber: '8184417656',
            establishedDate: 0,
            address: '1000 los angeles',
        },
        {
            name: 'Thrid Office',
            email: 'office1@test.com',
            phoneNumber: '8184417656',
            establishedDate: 0,
            address: '1000 los angeles',
        },
    ],
    agents: [
        {
            email: 'Agent1@test.com',
            firstName: 'Agent',
            lastName: 'One',
            address: '100 Los angeles',
            officeId: null,
            branchId: null,
        },
        {
            email: 'Agent2@test.com',
            firstName: 'Agent',
            lastName: 'Two',
            address: '100 Los angeles',
            officeId: null,
            branchId: null,
        },
        {
            email: 'Agent3@test.com',
            firstName: 'Agent',
            lastName: 'Three',
            address: '100 Los angeles',
            officeId: null,
            branchId: null,
        },
        {
            email: 'Agent4@test.com',
            firstName: 'Agent',
            lastName: 'Four',
            address: '100 Los angeles',
            officeId: null,
            branchId: null,
        },
    ],
    branches: [
        {
            officeId: null,
            name: 'Branch 1',
            email: 'branch1@test.com',
            phoneNumber: '2131122112',
            establishedDate: 0,
            address: '888 los angeles',
        },
        {
            officeId: null,
            name: 'Branch 2',
            email: 'branch2@test.com',
            phoneNumber: '2131122112',
            establishedDate: 0,
            address: '888 los angeles',
        },
        {
            officeId: null,
            name: 'Branch 3',
            email: 'branch3@test.com',
            phoneNumber: '2131122112',
            establishedDate: 0,
            address: '888 los angeles',
        },
        {
            officeId: null,
            name: 'Branch 4',
            email: 'branch4@test.com',
            phoneNumber: '2131122112',
            establishedDate: 0,
            address: '888 los angeles',
        },
    ],
    permissions: [
        {
            title: 'ALL_ACCESS',
            description: 'Used for super admin',
            code: 0,
        },
        {
            title: 'MANAGE_ROLES',
            description: 'Used for users to manage role system',
            code: 2,
        },
        {
            title: 'MANAGE_ADMINS',
            description: 'Used for users to manage admins',
            code: 3,
        },
        {
            title: 'OFFICE_MANAGEMENT',
            description: 'Can create, delete and update office related information',
            code: 4,
        },
        {
            title: 'TESTING',
            description: 'Can create, delete and update office related information',
            code: 5,
        },
        {
            title: 'TESTING AGAIN',
            description: 'Can create, delete and update office related information',
            code: 6,
        },
    ],
    roles: [
        {
            title: 'ALL_ACCESS',
            description: 'aaa',
            permissions: [],
        },
        {
            title: 'MANAGE_AGENT',
            description: 'bbb',
            permissions: [],
        },
        {
            title: 'MANAGE_OFFICE',
            description: 'xxx',
            permissions: [],
        },
        {
            title: 'MANAGE_BRANCH',
            description: 'yyy',
            permissions: [],
        },
    ],
};
