/**Create Global PayCode */
export const CREATE_PAYCODE_GLOBAL = 'CREATE_PAYCODE_GLOBAL'
export const CREATE_PAYCODE_GLOBAL_SUCCESS = 'CREATE_PAYCODE_GLOBAL_SUCCESS'

/**Get Global PayCode */
export const GET_PAYCODE_GLOBAL = 'GET_PAYCODE_GLOBAL'
export const GET_PAYCODE_GLOBAL_SUCCESS = 'GET_PAYCODE_GLOBAL_SUCCESS'

/**Edit Global PayCode by id */
export const EDIT_PAYCODE_BY_ID_GLOBAL = 'EDIT_PAYCODE_BY_ID_GLOBAL'
export const EDIT_PAYCODE_BY_ID_GLOBAL_SUCCESS = 'EDIT_PAYCODE_BY_ID_GLOBAL_SUCCESS'

/**Delete Global PayCode by id */
export const DELETE_PAYCODE_BY_ID_GLOBAL = 'DELETE_PAYCODE_BY_ID_GLOBAL'
export const DELETE_PAYCODE_BY_ID_GLOBAL_SUCCESS = 'DELETE_PAYCODE_BY_ID_GLOBAL_SUCCESS'

/**Create Global Overtime Settings */
export const CREATE_OVERTIME_SETTINGS_GLOBAL = 'CREATE_OVERTIME_SETTINGS_GLOBAL'
export const CREATE_OVERTIME_SETTINGS_GLOBAL_SUCCESS = 'CREATE_OVERTIME_SETTINGS_GLOBAL_SUCCESS'

/**Get Global Overtime Settings */
export const GET_OVERTIME_SETTINGS_GLOBAL = 'GET_OVERTIME_SETTINGS_GLOBAL'
export const GET_OVERTIME_SETTINGS_GLOBAL_SUCCESS = 'GET_OVERTIME_SETTINGS_GLOBAL_SUCCESS'

/**Edit Global Overtime Settings by id */
export const EDIT_OVERTIME_SETTINGS_BY_ID_GLOBAL = 'EDIT_OVERTIME_SETTINGS_BY_ID_GLOBAL'
export const EDIT_OVERTIME_SETTINGS_BY_ID_GLOBAL_SUCCESS = 'EDIT_OVERTIME_SETTINGS_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Overtime Settings by id */
export const DELETE_OVERTIME_SETTINGS_BY_ID_GLOBAL = 'DELETE_OVERTIME_SETTINGS_BY_ID_GLOBAL'
export const DELETE_OVERTIME_SETTINGS_BY_ID_GLOBAL_SUCCESS = 'DELETE_OVERTIME_SETTINGS_BY_ID_GLOBAL_SUCCESS'

