/**Create Global Credential */
export const CREATE_PAYCODE_GLOBAL = 'CREATE_PAYCODE_GLOBAL'
export const CREATE_PAYCODE_GLOBAL_SUCCESS = 'CREATE_PAYCODE_GLOBAL_SUCCESS'

/**Get Global Credential */
export const GET_PAYCODE_GLOBAL = 'GET_PAYCODE_GLOBAL'
export const GET_PAYCODE_GLOBAL_SUCCESS = 'GET_PAYCODE_GLOBAL_SUCCESS'

/**Edit Global Credential by id */
export const EDIT_PAYCODE_BY_ID_GLOBAL = 'EDIT_PAYCODE_BY_ID_GLOBAL'
export const EDIT_PAYCODE_BY_ID_GLOBAL_SUCCESS = 'EDIT_PAYCODE_BY_ID_GLOBAL_SUCCESS'

/**Delete Global Credential by id */
export const DELETE_PAYCODE_BY_ID_GLOBAL = 'DELETE_PAYCODE_BY_ID_GLOBAL'
export const DELETE_PAYCODE_BY_ID_GLOBAL_SUCCESS = 'DELETE_PAYCODE_BY_ID_GLOBAL_SUCCESS'